config/routes.rb
Rails.application.routes.draw do
	resources :messages

	root 'messages#index'
	

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :find_message, only: [:show,:edit, :update, :destroy]
	def index
		@messages=Message.all.order("created_at DESC")
	end

	def new
		@message=Message.new
	end

	def show
		
	end


	def create
		@message=Message.new(message_params)
		if @message.save
			redirect_to root_path
		else
			render 'new'
		end
			
		
	end

	private
		def message_params
			params.require(:message).permit(:title, :description)
		end

		def find_message
			@message=Message.find(params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%=simple_form_for @message do |f|%>

<%= f.input :title ,label:"Message Title"%>
<%= f.input :description ,label:"Describe "%>
<%= f.button :submit ,label:"Click to Submit"%>
<% end -%>

app/views/messages/index.html.erb
<h1>Message Board</h1>

<% @messages.each do |message|%>
	<h1> <%=message.title%> </h1>
	<% end -%>

	<%= link_to "new message", new_message_path%>

app/views/messages/new.html.erb
<h1>New Form</h1>>

<%= render 'form'%>

app/views/messages/show.html.erb
<h1>
	<%=@message.title%><br>
	<%=@message.description%>
</h1>